### ISSUE TITLE
glitches at karamja arena agility course

### ISSUE THREAD

**Issue by ReinierAarnink1996** [geheur/weapon-animation-replacer#10]
glitches at karamja arena agility course (scythe animation changed for whip), when using the obstacles

**Comment by ReinierAarnink1996** [comment]
glitches at ardy rooftop course too, my character disappears while on the obstacles

**Comment by geheur** [comment]
does your character regularly disappear and reappear when on the obstacle?

**Comment by ReinierAarnink1996** [comment]
> does your character regularly disappear and reappear when on the obstacle?

Yes

**Comment by geheur** [comment]
Might have something to do with having a pose animation frame greater than the number of pose animation frames in the animation? Can force something similar looking to this to happen by setting a pose animation with a low # of frames every client tick (ex 5800 is like, 2 frames, or 809 (11 frames) while wielding crossbow (15 frames)). Not sure if this is the same thing though.

Also, I've seen the player model disappearing intermittently while using certain animations swaps with certain weapons. I think it was elder maul standing pose, while wielding maybe rapier or whip or tent whip or dwh? don't remember exactly. Will have to check this and the obstacle thing when I have membership again.

**Comment by ReinierAarnink1996** [comment]
> Might have something to do with having a pose animation frame greater than the number of pose animation frames in the animation? Can force something similar looking to this to happen by setting a pose animation with a low # of frames every client tick (ex 5800 is like, 2 frames, or 809 (11 frames) while wielding crossbow (15 frames)). Not sure if this is the same thing though.
> 
> Also, I've seen the player model disappearing intermittently while using certain animations swaps with certain weapons. I think it was elder maul standing pose, while wielding maybe rapier or whip or tent whip or dwh? don't remember exactly. Will have to check this and the obstacle thing when I have membership again.

I was wearinf a Scythe of vitur and swapped it with a whip (stand, walk, all doesnt matter) and a snowball. But it doesnt matter which weapon I choose in my experience.

**Comment by geheur** [comment]
Assumed partially fixed due to setting pose at a lower level, remaining issues assumed to be the same as #16, closing in favor of #16.
