### ISSUE TITLE
Throwing Knifes wont animate

### ISSUE THREAD

**Issue by Soxxworld** [geheur/weapon-animation-replacer#21]
Hey man, can you fix it so that the throwing knifes will be animated??

**Comment by geheur** [comment]
which items are not working (specifically what throwing knives do you have equipped and what do you have set in the plugin?). Also are they poisoned?

**Comment by Soxxworld** [comment]
Dragon Knife p++ 

Yes, I used to used them with the d claw special animation. It won’t work now.

**Comment by geheur** [comment]
yeah I forgot to add poisoned knives originally; they have a different animation id as the non-poisoned version. Should be easy to fix.

**Comment by Soxxworld** [comment]
Please if you could do that I’d appreciate it greatly!

Let me know after so I can try it out.

**Comment by Soxxworld** [comment]
Status?

**Comment by Soxxworld** [comment]
???

**Comment by geheur** [comment]
yeah im doing that right now actually.

**Comment by Soxxworld** [comment]
Perfect.

**Comment by Soxxworld** [comment]
Please let me know after it’s done

**Comment by Soxxworld** [comment]
I

**Comment by geheur** [comment]
https://github.com/runelite/plugin-hub/pull/2439 it will be in when this is merged. version number will be 2.2.2

**Comment by Soxxworld** [comment]
Runelite has to update?

**Comment by Soxxworld** [comment]
Can you tell me how to activate the dragon knifes to animals like the d claws please?

**Comment by geheur** [comment]
The change I linked earlier isn't in yet. Also I don't know what you mean by animals.

**Comment by Soxxworld** [comment]
i didnt mean animals.

**Comment by Soxxworld** [comment]
When will it be in?? Will it be today?

**Comment by geheur** [comment]
idk when. whenever the runelite people get around to reviewing plugin hub updates.

**Comment by geheur** [comment]
This has been added.
