### ISSUE TITLE
Search function limited to 24

### ISSUE THREAD

**Issue by Friedea** [geheur/weapon-animation-replacer#27]
Hi! I am not sure how to get in touch with the creator of this wonderful plugin so I thought I could try opening a small issue/suggestion here.

Basically, the searching function for the display transmog is limited to 24, so if I were to search for the Keldagrim Blue Skirt (which is ID'd only by "Skirt") it is hidden beyond the 24 search limit display of the other skirts like rune plateskirts and their variants etc. 

Proposition - To allow a scroll down display like the G.E search function to display >24 items. P.S. another side benefit is to let people browse generic terms so they can find matches for their outfit better! 

Thank you for taking the time to read this, it is a wonderful plugin and thanks a bunch for working on it!

**Comment by geheur** [comment]
I was aware of this issue but I hadn't run into any issues where I couldn't select an item so I never fixed it.

For now you can use the item id (5052 I think).

**Comment by Friedea** [comment]
Okay that works too, didn't know you can search by ID. Thanks very much!

**Comment by geheur** [comment]
d3994a88af899ba7c3315de810b2a6c43be4c6ae adds this, when https://github.com/runelite/plugin-hub/pull/4107 is merged.
