### ISSUE TITLE
Attack animation override is not working for Osmumtens Fang!

### ISSUE THREAD

**Issue by Darkchaoss** [geheur/weapon-animation-replacer#29]
Hello, I love this plugin, but I'm trying to change the attack animation to Osmumtens Fang and it will not change. Stand/move animation changes. Attack preview shows the right attack, but the attack animation won't apply when fighting something. Any help is appreciated!

**Comment by geheur** [comment]
osmumten's fang attack and spec animations aren't in the plugin (there's no way to identify which animations are attack animations without listing every id in the plugin). I can add it.

**Comment by Darkchaoss** [comment]
That would be sick! Loving the plugin, makes skilling and scaping super enjoyable thank you for your hard work!

**Comment by geheur** [comment]
added in version 2.2.6
