### ISSUE TITLE
Allow items to be equipped that haven't yet been picked up by the runelite wiki scraper.

### ISSUE THREAD

**Issue by yungando** [geheur/weapon-animation-replacer#31]
Please can you add the 10th Birthday Event rewards?

They don't seem to be appearing, specifically the gnome child backpack and plushie don't show up in the model swap search.

Thanks

**Comment by yungando** [comment]
I know it isn't up to you, but do you why the new wiki scraper data hasn't been merged, or when it will be merged? Looks like the scraper has ran a few times since the start of the birthday event, but the data is on a different branch.

Thanks

**Comment by geheur** [comment]
I asked in runelite discord and abex merged it. The items show up in the plugin now.

**Comment by geheur** [comment]
https://github.com/runelite/plugin-hub/pull/4198 will be added when this PR is closed.

**Comment by geheur** [comment]
It has now been merged and will be available in version 3.1.0.
