### ISSUE TITLE
replacing specific attack animations replaces all attack animations instead

### ISSUE THREAD

**Issue by vbojilov** [geheur/weapon-animation-replacer#33]
-selecting to replace the special attack of a weapon with a different animation causes all attacks (regular and special) to be changed instead of only the special attack animation 

-attempting to set separate animations for different combat styles does not work; only one of the combat style settings gets applied and overrides the others

-the special attack of osmumten's fang isn't able to be changed, even with the above two issues considered it still uses the default animation. 

-in the list of animations available osmumten's fang is missing the slash animation

**Comment by geheur** [comment]
1) does happen, and the current behavior seems incorrect.
2) what weapon are you doing this with? I tried with a blurite sword, and was able to override stab and slash animations with different attack animations. Are you trying this with a weapon that uses the same animation for different styles? I suppose I could check your own attack style you have set to differentiate these.
3) I don't think I can change spec animations either. sounds like a bug.
4) osmumten's fang has only one non-special attack animation afaik (I don't own one), so I didn't bother to list them separately.

**Comment by geheur** [comment]
actually I am wrong on 3, I was testing with the candle dagger whose animation is not classed as a spec. Can you get me the osmumten's fang spec id, or show it to me in-game (rsn "Laiduf")?

**Comment by geheur** [comment]
nvm I got someone else to do it. it uses a different animation id that looks identical.

**Comment by geheur** [comment]
to be fixed in 3.2.1 https://github.com/runelite/plugin-hub/pull/4247

**Comment by geheur** [comment]
should be fixed in 3.2.1
