### ISSUE TITLE
tbow + dragon arrows projectile swap bug

### ISSUE THREAD

**Issue by Zaphyrim** [geheur/weapon-animation-replacer#35]
Rune arrows work as expected:
![image](https://user-images.githubusercontent.com/131311012/233211247-8eaf34e8-b85d-4240-9c97-59fdccc99b49.png)

Dragon arrows do not show any swap:
![image](https://user-images.githubusercontent.com/131311012/233211381-7ec096b4-b6b3-4062-92ce-83ef07bfcaf4.png)

**Comment by geheur** [comment]
so... I can't afford to shoot dragon arrows (dark bow shoots 2, different thing). can you show me you shooting them in-game? rsn "Laiduf".

**Comment by geheur** [comment]
nvm someone else got me these values, I just forgot to add them.

**Comment by geheur** [comment]
added https://github.com/runelite/plugin-hub/pull/4247 to be released in 3.2.1

**Comment by geheur** [comment]
should be fixed in 3.2.1
