### ISSUE TITLE
No projectile listed for Tumeken's Shadow

### ISSUE THREAD

**Issue by Zaphyrim** [geheur/weapon-animation-replacer#36]
Tried to replace the Shadow projectile with a wind strike but couldn't find it on any page.

Would expect it to appear after the sangs on this page:
![image](https://user-images.githubusercontent.com/131311012/233212151-2734b3ff-a696-44d8-bb35-c6f66edea8eb.png)

**Comment by geheur** [comment]
added https://github.com/runelite/plugin-hub/pull/4247 to be released in 3.2.1
it won't be after the sangs (due to some bad decisions I made that aren't trivial to fix) but you can search for it by name.

**Comment by geheur** [comment]
should be fixed in 3.2.1
