### ISSUE TITLE
Texture bugged

### ISSUE THREAD

**Issue by yuriarsn** [geheur/weapon-animation-replacer#39]
the textures are bugged and sometimes i put a transmog and my weapon becomes invisible

**Comment by geheur** [comment]
can you show what you're setting in the side panel and what it looks like in game?

**Comment by yuriarsn** [comment]
i opened runelite again and they came back, i think it was the client
error. i closed the post

thank u!

Em qui., 10 de ago. de 2023 01:24, geheur ***@***.***>
escreveu:
