### ISSUE TITLE
Sanguine Torva Full Helm Graphical Bug

### ISSUE THREAD

**Issue by longflin** [geheur/weapon-animation-replacer#40]
When transmoging Regular Torva helm into the Blood Torva variant, the helmet has graphical glitches.

https://i.imgur.com/0jfJlSf.png

**Comment by geheur** [comment]
use the "hide/show slot" section of the model replacement search to hide hair and jaw, until I fix this.

**Comment by geheur** [comment]
I think this has been fixed.
