### ISSUE TITLE
Soulreaper axe not working

### ISSUE THREAD

**Issue by MaxouOS** [geheur/weapon-animation-replacer#41]
Soulreaper axe can be visually replaced by other items, but the attack animation stays the same. Stand/Move animations work perfectly fine. I'm guessing it's because of the new attack animation, like for fang in https://github.com/geheur/weapon-animation-replacer/issues/29. 

Love your work!

**Comment by geheur** [comment]
[[Do you happen to know what animations it uses? both for attack/defend and stand/move.

I don't have membership and I don't have the axe.](https://github.com/runelite/plugin-hub/pull/4847)](https://github.com/runelite/plugin-hub/pull/4847)
