### ISSUE TITLE
No Saradomin Sword?

### ISSUE THREAD

**Issue by CAREFACE720** [geheur/weapon-animation-replacer#42]
Was trying to replace Voidwaker spec animation to the regular Sara Sword spec animation since its the closest of the rs2 animation, but I don't see the sword anywhere in the list?

**Comment by geheur** [comment]
I never added the spec. I've never owned a saradomin sword. Although for the rest of the animations, I think they are the same as the godswords.

I can add it. although I don't have anything set up to add the lightning gfx atm.

**Comment by CAREFACE720** [comment]
Yeah, its just the spec that have its unique animation. Well, take your time, I was just wondering, but yeah, would be great!

The lightning + sound effect is almost identical to the old korasi spec if I remember correctly.

**Comment by CAREFACE720** [comment]
> I never added the spec. I've never owned a saradomin sword. Although for the rest of the animations, I think they are the same as the godswords.
> 
> I can add it. although I don't have anything set up to add the lightning gfx atm.

is it not possible to show the current weapon being held instead of the sara sword on the spec? also when you spec while moving the legs do not move, which I assume its animation layered and missing the bottom part animation?

**Comment by geheur** [comment]
Oh, I didn't notice that it had the weapon hardcoded into the animation. That does suck, but that's just how some animations are.

Runelite doesn't have anything to easily deal with it. I could ask if adam could add API for it but he seems pretty busy.
