### ISSUE TITLE
Swapping fang stab attack animation doesnt work

### ISSUE THREAD

**Issue by pukapy** [geheur/weapon-animation-replacer#43]
Title pretty much, trying to swap the fangs animation stab to scythe for example doesnt work and it still stabs with the scythe
![image](https://github.com/geheur/weapon-animation-replacer/assets/15847800/57da1329-a3e9-4506-a4c4-e600f656f694)

**Comment by geheur** [comment]
I mistakenly didn't mark the animation as a stab animation. Changing "Replace" to "Attack" might work until it's fixed. I don't have a fang so I can't test it.
btw do you happen to know the slash animation id? I never recorded that one.

**Comment by pukapy** [comment]
Changing it to attack doesnt work either.
You mean the ID for the scythe? i dont have one but the visual sounds plugin for the fang says stabsword_slash 2548 for Slash

**Comment by geheur** [comment]
visual sounds is showing sound ids.

if you want to log the osmumten's fang stab/slash animation ids, you could install my "weapon charges" plugin, click the "log data" checkbox, do the animation, then check your logs for it.

I don't think I need those ids though, I think I know what the issue is. I'll see what I can do to fix it.

**Comment by pukapy** [comment]
```
[Client] INFO  com.weaponcharges.Devtools - 403: animation changed: 9471
[Client] INFO  com.weaponcharges.Devtools - 405: animation changed: -1
[Client] INFO  com.weaponcharges.Devtools - 410: animation changed: 9471
[Client] INFO  com.weaponcharges.Devtools - 412: animation changed: -1
```

**Comment by geheur** [comment]
I need the slash animation id, not the stab one.

**Comment by pukapy** [comment]
```
[Client] INFO  com.weaponcharges.Devtools - 73: animation changed: 390
[Client] INFO  com.weaponcharges.Devtools - 75: animation changed: -1
```
for the fang slash animation

**Comment by geheur** [comment]
Alright, I'll put it in in the next release.

**Comment by geheur** [comment]
I think I added this about a month ago.
