### ISSUE TITLE
Sidebar icon missing? Also a question about hiding items

### ISSUE THREAD

**Issue by LackOfCreativiT** [geheur/weapon-animation-replacer#44]
I installed this and was using it for a bit, then I uninstalled. I have since reinstalled it, and the sidebar icon is gone with seemingly no way to make it come back. (I've made sure the hide button box is unticked) I've tried reinstalling runelite, uninstalling other plugins, logging into a different account, nothing seems to be fixing this.

![image](https://github.com/geheur/weapon-animation-replacer/assets/96823707/ee68254f-0ae1-4c56-b703-f638518902a1) included an image of sidebar not existing

unrelated to the real problem in that the ability to use the plugin just being gone, I like this transmog solution the most compared to the other options out there. However, I do have one complaint with the system: there seems to be no way to show default clothing. The "hide" option certainly exists, but unless there was something wrong on my end back when I was able to open the menu to use the plugin, the hide options would hide the entire body part. Is that user error or is that just how it is? I was able to hide the graceful hood and see my face/hair, but no dice on the rest.

Thank you for your time and thank you for your hard work. Going to try reinstalling again and deleting every file related to runelite to see if that does anything.

**Comment by LackOfCreativiT** [comment]
No dice, completely nuking runelite did not accomplish anything on the front of making the icon come back.

Perhaps it isn't something on my end then?

**Comment by geheur** [comment]
can you post your `client.log` file? You can right-click the runelite screenshot button, click open folder, and go up one folder to see the "logs" directory, and `client.log` is in there. The button should be visible.

As for the showing base items, base items are not something that I've added, although I would like to add it in the future. I only have show hair/jaw/arms because this used to be necessary to make it so that you didn't have your hair clipping out of a full helmet.

**Comment by geheur** [comment]
also does "deleting every file in runelite" include making a new profile?

**Comment by LackOfCreativiT** [comment]
[client.log](https://github.com/geheur/weapon-animation-replacer/files/12704877/client.log)
Sorry, almost forgot about this reply, that's why it's late. I believe I deleted every single file related to runelite on my PC (found using [Everything](https://www.voidtools.com/forum/viewtopic.php?t=9787). I'll try one more time making 100% sure that I delete the profile, just for conclusiveness.

Okay, turns out that now it's there after making sure every single file is gone (which is odd because I thought I did this already, but I digress). After reinstalling again and enabling my cloud profile, the issue appears to persist. So it's something to do with my profile, which I'd understand if you didn't wanna troubleshoot that lol

**Comment by geheur** [comment]
can you post the lines in `.runelite/profiles2/yourprofilename-189023102837018923.properties` that start with "WeaponAnimationReplacer"?

**Comment by LackOfCreativiT** [comment]
I'll send the file when I'm home in a couple hours, thanks for helping.

**Comment by LackOfCreativiT** [comment]
> can you post the lines in `.runelite/profiles2/yourprofilename-189023102837018923.properties` that start with "WeaponAnimationReplacer"?

Here they are:

WeaponAnimationReplacer.transmogSets=NOT_JSONnull
WeaponAnimationReplacer.hideSidePanel=false
runelite.weaponanimationreplacerplugin=true
WeaponAnimationReplacer.serialVersion=2
WeaponAnimationReplacer.showUnequippableItems=false

**Comment by geheur** [comment]
Hmm that's weird. I'll see if I can find out where that happened.

In the meantime, you may be able to just delete the "WeaponAnimationReplacer.transmogSets=NOT_JSONnull" line and have it work again. Sorry for the inconvenience 👍

**Comment by LackOfCreativiT** [comment]
Yep, that did it.

Thanks for the help!
