### ISSUE TITLE
Projectile animation swap doesn't work

### ISSUE THREAD

**Issue by codhip** [geheur/weapon-animation-replacer#50]
I'm trying to change the bolt projectile animation to a javelin animation and it doesn't work, nor does any spell animation swap work. I have had no success with any projectile. Just wondering if this is a known issue and whether or not there's a fix. 

Thanks.

**Comment by geheur** [comment]
which weapon and which bolt type is this, and is it in pvp or pvm?

**Comment by codhip** [comment]
> which weapon and which bolt type is this, and is it in pvp or pvm? zcb in pvp is a known issue.

The weapon is the dragon crossbow, and the bolt types were ruby dragon bolts (e) and diamond dragon bolts (e). This would be PvM, i haven't tried it in PvP yet. I actually did a little bit of troubleshooting and I discovered that the animation swap does not work for the dragon bolts, but works for every other bolt type I've tried thus far.

**Comment by geheur** [comment]
can you click on custom projectile, open the projectile ids window, shoot some bolts, and post the results here?
![image](https://github.com/geheur/weapon-animation-replacer/assets/41499327/744e482c-2845-4195-8cd9-2738d91558f7)

**Comment by codhip** [comment]
![weapon swapper troubleshooting](https://github.com/geheur/weapon-animation-replacer/assets/157996425/f601ecf2-eaec-45db-a543-4fa32de40d07)


I haven't changed any of the projectile values. The projectile ID changed from 1301 to 1468 once I hit "use".

**Comment by geheur** [comment]
This is probably due to dragon bolts having a different projectile. I submitted a fix (3.6.1). Let me know if it works.

**Comment by geheur** [comment]
I think I added this.
