### ISSUE TITLE
Hair clips through hood, Dizana's Max Hood

### ISSUE THREAD

**Issue by Ballum7** [geheur/weapon-animation-replacer#55]
When transmoging a piece of head gear with Dizana's max hood
Causes hair to clip through the hood
![image_2024-07-08_103306350](https://github.com/geheur/weapon-animation-replacer/assets/175007115/192fba72-767a-4fa7-9fa5-5840f5ad8ab4)

**Comment by geheur** [comment]
if you restart the plugin, does it fix itself?
