### ISSUE TITLE
Weapon/Gear/Anim Replacer - Jaws not working correctly on female models

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [geheur/weapon-animation-replacer#58]
If you use the plugin to change or hide your helmet with a female character it always hides your jaw resulting in a big hole in your characters head/face, I presume this has something to do with plugin not building the head correctly after they added the new jaws for females?

Video of issue:
https://github.com/user-attachments/assets/8dd79d1d-8b96-4b1e-bed8-d1af9b254a43

**Comment by geheur** [comment]
it probably is yeah.

**Comment by Jin-Jiyunsun** [comment]
Any update on this? I love using the plugin to hide my helmet but it looks really off right now

**Comment by geheur** [comment]
Should be fixed in 3.7.3.

**Comment by Jin-Jiyunsun** [comment]
Wonderful, thank you.
