### ISSUE TITLE
Dual Macuahuitl swap with scythe

### ISSUE THREAD

**Issue by ZamorakBrews** [geheur/weapon-animation-replacer#62]
The attack animation simply will not work, i can get everything else to work but the attack, it still does the dual attack animation.

**Comment by geheur** [comment]
do you know the animation ids of the macuahuitl?

**Comment by ZamorakBrews** [comment]
I believe its the same as torags hammers ~2068.....

**Comment by geheur** [comment]
if it was the same as torag's hammers it would already work. can you use the identificator plugin to find the animation id?

**Comment by ZamorakBrews** [comment]
10989 is Attack animation ID

**Comment by geheur** [comment]
should be available now if you restart the plugin.
