### ISSUE TITLE
Missing jaw when hiding helmet

### ISSUE THREAD

**Issue by dino5371** [geheur/weapon-animation-replacer#63]
As the title says, when hiding the helmet the jaw just goes poof. I tried to make it use the "show jaw" thing, both by itself and to replace a hidden jaw, to no avail. Lovely plugin though, very fun to use!

![MissingJaw](https://github.com/user-attachments/assets/6dba24a2-ee2e-4896-9677-e676a9cd494e)

**Comment by geheur** [comment]
Will be fixed in the next update.
For now try wearing a facemask :)

**Comment by dino5371** [comment]
Oh face mask is a sick idea, I didn't even think of it! Thank you!

**Comment by geheur** [comment]
Should be fixed in 3.7.3.
