### ISSUE TITLE
PLEASE FIX

### ISSUE THREAD

**Issue by 2Soxx** [geheur/weapon-animation-replacer#8]
When I use my throwing knifes, the animations don't work for some reason anymore. Please fix this for me.

**Comment by geheur** [comment]
This works fine for me with rune knives:
![image](https://user-images.githubusercontent.com/41499327/120881386-9bca9800-c585-11eb-95dc-7f96101b6cdd.png)

Include the config you have set and what weapon you're using it with and what animations aren't working or I can't help with this.

**Comment by 2Soxx** [comment]
Even with that one it doesn’t do the animation when I throw the knives. 

See. I took a video.

**Comment by geheur** [comment]
I don't see a video.

**Comment by 2Soxx** [comment]
Look at the attachment

**Comment by 2Soxx** [comment]
Says it’s too large. Do you have disc or something?

**Comment by geheur** [comment]
geheur#4508
