### ISSUE TITLE
Godsword animation bugs

### ISSUE THREAD

**Issue by Heirem** [geheur/weapon-animation-replacer#9]
Godsword idle, walk/run, and defending animations all glitch out.

**Comment by geheur** [comment]
I'm guessing this is the thing where the framerate or maybe cycle length of the animation your character is actually doing is different from the one the godsword animation override does, so it repeats too early.

This is probably fixable, although I'd have to ask for some extra API to be added.

**Comment by Heirem** [comment]
Good to hear. Thank you.

**Comment by geheur** [comment]
API has been added to runelite that can be used to fix this, possibly also #10, #5, and maybe even #6 if I'm lucky.

**Comment by Heirem** [comment]
Awesome, thanks!
